### ISSUE TITLE
React Swiper with Universal

### ISSUE THREAD

**Issue by beckmeindia** [nickpisacane/react-dynamic-swiper#3]
Hey I am getting this Error on running in React Universal environment. 

As per the error: this is the line that is throwing that error:   
static propTypes = Object.assign({
Apparently there is a problem with the equals sign

ERROR in ./~/react-dynamic-swiper/src/swiper.js
Module parse failed: C:\Users\gemini\Desktop\react-universal\node_modules\react-dynamic-swiper\src\swiper.js Unexpected token (15:19)

You may need an appropriate loader to handle this file type.

SyntaxError: Unexpected token (15:19)
    at Parser.pp$4.raise (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.expect (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:597:28)
    at Parser.pp$3.parseMethod (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:2071:10)
    at Parser.pp$1.parseClassMethod (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1137:25)
    at Parser.pp$1.parseClass (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1118:14)
    at Parser.pp$3.parseExprAtom (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1813:19)
    at Parser.pp$3.parseExprSubscripts (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\gemini\Desktop\react-universal\node_modules\acorn\dist\acorn.js:1597:21)
 @ ./~/react-dynamic-swiper/lib/SwiperLib.js 12:24-41

Could you please suggest how I should use the library?

Thanks

**Comment by nickpisacane** [comment]
It looks like you are somehow requiring/importing directly from the `src` directory, which is using es6+ features that may not be compatible with your babel configuration, possibly [class properties](https://babeljs.io/docs/plugins/transform-class-properties/). However, this shouldn't be an issue as everything in `src` is transpiled to es5 in the `lib` directory upon publishing. It should be compatible with your boilerplate. How are you importing `react-dynamic-swiper`, more specifically, what path(s)?

**Comment by beckmeindia** [comment]
Hi Nick,
  Thanks for the quick reply. I am using
 import { Swiper, Slide } from 'react-dynamic-swiper'

Also I have checked that both es2015 and react arr included in the webpack dev config in loaders against jsx

**Comment by nickpisacane** [comment]
This is very weird. I have tested on Ubuntu, and everything is running fine, but fails on Windows. I will have more time to look into this tomorrow. This seems to be an issue relating to module resolution.

**Comment by nickpisacane** [comment]
Looks like removing the `src` directory from the NPM package fixes this. Still not sure why this was only an issue on Windows, and further, with webpack (server-side importing/requiring `'react-dynamic-swiper'` worked fine), but this should do it for now. Install `react-dynamic-swiper@1.0.5` and you should be good to go! Please open another issue if this persists, thanks.

**Comment by beckmeindia** [comment]
This works like a charm now!
Thanks a lot once again for your time.

**Comment by nickpisacane** [comment]
Not a problem. Glad you are making use of react-dynamic-swiper.
